name: Cleanup workload k8s
on: 
  workflow_dispatch:

jobs:
  apply_k8s:
    name: Verify K8s Service Account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - name: Create/Verify `.kube` directory
        run: mkdir -p ~/.kube/
      - name: Create kubectl config
        run: |
          cat << EOF >> ~/.kube/kubeconfig.yaml
          ${{ secrets.KUBECONFIG }}
          EOF
      - name: Cleanup workload k8s
        run: |
          KUBECONFIG=~/.kube/kubeconfig.yaml kubectl delete -f ops/
